#RadiationWorld Configuration File

#Radiation
Radiation:

    #Level of radiation required to kill
    Lethal: 100

    #Overworld settings
    Overworld:
        #BGRad (per second)
        Background: 5.0
        #Haven settings
        Haven:
            #Radius of haven
            Radius: 150
            #Dist takes to recieve full BGRadiation
            Buffer: 850

    #The Nether settings
    Nether:
        #BGRad (per second)
        Background: 1.0

    #The End settings
    End:
        #BGRad (per second)
        Background: 0.0

    #SunRad (per second)
    Sun: 0.5

    #RadRecovery (per second)
    Recovery: 0.3

    #Resists (percent)
    Resists:
        Leather: 0.65
        Gold: 0.80
        Iron: 0.50
        Diamond: 0.40