
name: RadiationWorld
version: 1.0
description: Fills the world with deadly radiation and corresponding features.
author: RossGosling

main: uk.co.cherrygoose.radiationworld.Main
database: false

commands: